require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 80

# RSpec Cop Configuration

Metrics/BlockLength:
  AllowedMethods:
    - RSpec.describe
    - before
    - context

RSpec/IndexedLet:
  Enabled: false  # stop telling me not to use examples like [1,2,3].

# Gemspec Cop Configuration

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec